INTEX_2/Components/FilterViewComponent.cs
using INTEX_2.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace INTEX_2.Components
{
    public class FilterViewComponent : ViewComponent
    {
        private ICrashRepository repo { get; set; }
        public FilterViewComponent(ICrashRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedFilter = RouteData?.Values["accidentFilter"];

            var severity = repo.Crashes
                .Select(x => x.crash_severity_id)
                .Distinct()
                .OrderBy(x => x);

            return View(severity);
        }
    }
}

INTEX_2/Controllers/HomeController.cs
using INTEX_2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using INTEX_2.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace INTEX_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ICrashRepository repo { get; set; }

        public HomeController(ILogger<HomeController> logger, ICrashRepository temp)
        {
            _logger = logger;
            repo = temp;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Accidents(int accidentFilter, int pageNum = 1)
        {
            int pageSize = 20;

            ViewBag.pageNumber = pageNum;
            ViewBag.numPages = (int) Math.Ceiling((double) repo.Crashes.Count() / pageSize);

            var x = new CrashViewModel
            {
                Crashes = repo.Crashes
                .Where(c => c.crash_severity_id == accidentFilter || accidentFilter == 0)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumCrashes = (accidentFilter == 0 ? repo.Crashes.Count() : repo.Crashes.Where(c => c.crash_severity_id == accidentFilter).Count()),
                    CrashesPerPage = pageSize,
                    CurrentPage = pageNum,
                    
                }
            };

            return View(x);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        public IActionResult AccidentDetails(int recordId)
        {

            var singleCrash = repo.Crashes.FirstOrDefault(x => x.crash_id == recordId);
            

            return View(singleCrash);
        }


        

    }
}

INTEX_2/Controllers/PredictionController.cs
using INTEX_2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace INTEX_2.Controllers
{
    public class PredictionController : Controller
    {

        private InferenceSession _session;

        public PredictionController(InferenceSession session)
        {
            _session = session;
        }

        [HttpGet]
        public IActionResult LookingAhead()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Score(CrashSeverity data)
        {
            var result = _session.Run(new List<NamedOnnxValue>
            {
                NamedOnnxValue.CreateFromTensor("float_input", data.AsTensor())
            });
            Tensor<long> score = result.First().AsTensor<long>();
            var prediction = new Prediction { PredictedValue = score.Last() };
            result.Dispose();
            return View("Score", prediction);
        }

 
    }
}

INTEX_2/Views/Home/AccidentDetails.cshtml
@{
    ViewData["Title"] = "Accident Details";
}

@model Crash

<div class="home-banner">
    <div class="container col-7 text-center">
        <h2 class="display-5 indextitle">Crash Details</h2>
    </div>
</div>
<br />
<div class="container col-9">
    <div class="row">
        <div class="col card ">
            <h2 class="pl-2">Location Information</h2>
            <div class="text-left  pl-2">
                <dl>
                    <dt>Crash Date: </dt>
                    <dd>@Model.crash_datetime</dd>

                    <dt>Route: </dt>
                    <dd>@Model.route</dd>

                    <dt>Main Road: </dt>
                    <dd>@Model.main_road</dd>

                    <dt>City: </dt>
                    <dd>@Model.city</dd>

                    <dt>County: </dt>
                    <dd>@Model.county_name</dd>

                    <dt>Milemarker: </dt>
                    <dd>@Model.milepoint</dd>

                    <dt>Latitude: </dt>
                    <dd>@Model.lat_utm_y</dd>

                    <dt>Longitude: </dt>
                    <dd>@Model.long_utm_x</dd>
                </dl>
            </div>
        </div>

        <div class="col">
            <h2>Crash Conditions</h2>
            <dl class="list-group">
                <div class="list-group-item ">
                <dt class="inline-stuff">
                    Work Zone Related:
                </dt>
                @if (@Model.work_zone_related == 1)
                {
                    <dd class="inline-stuff">True</dd>

                }
                else
                {
                    <dd class="inline-stuff">False</dd>
                }
        </div>





        <div class="list-group-item ">
            <dt class="inline-stuff">
                Pedestrian Involved:
            </dt>
            @if (@Model.pedestrian_involved == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }
        </div>

        <div class="list-group-item">
            <dt class="inline-stuff">
                Bicycdtst Involved:
            </dt>
            @if (@Model.bicyclist_involved == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }
        </div>

        <div class="list-group-item ">
            <dt class="inline-stuff">
                Motorcycle Involved:
            </dt>

            @if (@Model.motorcycle_involved == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }
        </div>

        <div class="list-group-item ">
            <dt class="inline-stuff">
                Improper Restraint:
            </dt>
            @if (@Model.improper_restraint == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }
        </div>

        <div class="list-group-item ">
            <dt class="inline-stuff">
                Unrestrained:
            </dt>
            @if (@Model.unrestrained == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }
        </div>

        <div class="list-group-item ">
            <dt class="inline-stuff">
                DUI:
            </dt>
            @if (@Model.dui == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }
        </div>

        <div class="list-group-item ">
            <dt class="inline-stuff">
                Intersection Related:
            </dt>
            @if (@Model.intersection_related == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }
        </div>

        <div class="list-group-item ">
            <dt class="inline-stuff">
                Wild Animal Related:
            </dt>
            @if (@Model.wild_animal_related == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }
        </div>




        </dl>

    </div>
    <div class="col">
        <dl>

            <div class="list-group-item ">
            <dt class="inline-stuff">
                Domestic Animal Related:
            </dt>
            @if (@Model.domestic_animal_related == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }

    </div>

    <div class="list-group-item ">
        <dt class="inline-stuff">
            Overturn Rollover:
        </dt>
        @if (@Model.overturn_rollover == 1)
        {
            <dd class="inline-stuff">True</dd>
        }
        else
        {
            <dd class="inline-stuff">False</dd>
        }

    </div>

    <div class="list-group-item ">
        <dt class="inline-stuff">
            Commercial Motor Vehicle Involved:
            @if (@Model.commercial_motor_veh_involved == 1)
            {
                <dd class="inline-stuff">True</dd>
            }
            else
            {
                <dd class="inline-stuff">False</dd>
            }
        </dt>
    </div>

    <div class="list-group-item ">
        <dt class="inline-stuff">
            Teenage Driver Involved:
        </dt>
        @if (@Model.teenage_driver_involved == 1)
        {
            <dd class="inline-stuff">True</dd>
        }
        else
        {
            <dd class="inline-stuff">False</dd>
        }

    </div>

    <div class="list-group-item ">
        <dt class="inline-stuff">
            Older Driver Involved:
        </dt>
        @if (@Model.older_driver_involved == 1)
        {
            <dd class="inline-stuff">True</dd>
        }
        else
        {
            <dd class="inline-stuff">False</dd>
        }

    </div>

    <div class="list-group-item ">
        <dt class="inline-stuff">
            Night/Dark Condition:
        </dt>
        @if (@Model.night_dark_condition == 1)
        {
            <dd class="inline-stuff">True</dd>
        }
        else
        {
            <dd class="inline-stuff">False</dd>
        }

    </div>

    <div class="list-group-item ">
        <dt class="inline-stuff">
            Single Vehicle:
        </dt>
        @if (@Model.single_vehicle == 1)
        {
            <dd class="inline-stuff">True</dd>
        }
        else
        {
            <dd class="inline-stuff">False</dd>
        }

    </div>

    <div class="list-group-item ">

        <dt class="inline-stuff">
            Distracted Driving:
        </dt>
        @if (@Model.distracted_driving == 1)
        {
            <dd class="inline-stuff">True</dd>
        }
        else
        {
            <dd class="inline-stuff">False</dd>
        }

    </div>

    <div class="list-group-item ">
        <dt class="inline-stuff">
            Drowsy Driving:
        </dt>
        @if (@Model.drowsy_driving == 1)
        {
            <dd class="inline-stuff">True</dd>
        }
        else
        {
            <dd class="inline-stuff">False</dd>
        }

    </div>

    <div class="list-group-item ">
        <dt class="inline-stuff">
            Roadway Departure:
        </dt>
        @if (@Model.roadway_departure == 1)
        {
            <dd class="inline-stuff">True</dd>
        }
        else
        {
            <dd class="inline-stuff">False</dd>
        }

    </div>
    </dl>
</div>
</div>
</div>

INTEX_2/Views/Home/Accidents.cshtml
@{
    ViewData["Title"] = "Accidents Summary";
}

@model CrashViewModel
    <div class="container col-10">
        <div class="">
            <div class="m-1 p-1">

                <div class="text-white">
                    <h2>Accident Summary</h2>
                    <vc:filter></vc:filter>
                </div>

                <div>
                    <table class="table table-responsive-sm table-striped table-hover">
                        <thead>
                            <tr class="table-light">
                                <th>Crash Time</th>
                                <th>Route</th>
                                <th>Main Road</th>
                                <th>City</th>
                                <th>County Name</th>
                                <th>Crash Severity</th>
                                <th>Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Crash c in Model.Crashes)
                            {
                                <tr>
                                    <partial name="AccidentSummary" model="c" />
                                </tr>

                            }

                        </tbody>
                    </table>

                    <div>
                        Page @ViewBag.pageNumber of @Model.PageInfo.TotalPages
                    </div>
                    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                        <div class="btn-group me-2" role="group" aria-label="First group" page-model="@Model.PageInfo" page-action="Accidents">
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

INTEX_2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Wrong Way Crash Prevention Home";
}

<div class=" text-center  ">
    <div class="home-banner">

        <br />
        <h2 class="display-4 indextitle">Wrong Way Crash Prevention | Utah</h2>
        <br /><br />

        <div class="container col-7 text-left">

            <h4 class="text-white"> Welcome to the Utah Wrong-Way Crash Prevention info center.</h4>
            <br />
            <p class="text-white">
                This site is a repository for Utah crash/roadway incident data from 2016-2019.
                By following the “Accident Summary” tab, you will view the entire database. You
                will be able to filter this database by crash severity. This database can help 
                lawmakers understand Utah roadways better and make informed decisions. Additionally, 
                our "Looking Ahead" page displays an interactive predictor for crash severity. (If you're 
                looking for a specific word, take a look at the bottom of the 'Privacy' page)
            </p>
            <br />
        </div>
    </div>
    <br />
        <section id="services" class="container">
            <h2 class="text-center display-5">Our Serivces</h2>
            <br />
            <div class="row text-center">
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <img class="card-img-top" src="~/img/crash_image.jpg" alt="Design">
                        <div class="card-body">
                            <h4 class="card-title">Accident Summary</h4>
                            <p class="card-text">
                                Hands on expereience with data concerning accidents that have
                                occurred from 2016-2019. 
                            </p>
                        </div>
                        <div class="card-footer py-4">
                            <a asp-action="Accidents" class="btn btn-success">See Accident Summary &raquo;</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <img class="card-img-top" src="~/img/Customer-Privacy-Policy.jpg" alt="Development">
                        <div class="card-body">
                            <h4 class="card-title">Privacy Policy</h4>
                            <p class="card-text">
                                We know the value of privacy and constantly strive to handle your information with care.
                            </p>
                        </div>
                        <div class="card-footer py-4">
                            <a asp-action="Privacy" class="btn btn-success">See Privacy Policy &raquo;</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        <img class="card-img-top" src="~/img/analyticsimg.jpg" alt="Analytics">
                        <div class="card-body">
                            <h4 class="card-title">Analytics</h4>
                            <p class="card-text">
                                Learn more about what the leading factors of wrong way crashes are and how you can help prevent them
                            </p>
                        </div>
                        <div class="card-footer py-4">
                            <a asp-controller="Prediction" asp-action="LookingAhead" class="btn btn-success">Go To Analytics &raquo;</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
</div>